[theme]
primaryColor = "#d4af37"
backgroundColor = "#f5f7fa"
secondaryBackgroundColor = "#ffffff"
textColor = "#000000"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
maxUploadSize = 200
enableCORS = false
enableXsrfProtection = true

[runner]
magicEnabled = false

[client]
showErrorDetails = true
